Feature/simplify permissions/118
tomsksoft-llc/cis1-webui-native-srv-cpp pull request #119
Opened 2020-03-19 09:56 UTC by sergeyboyko0791

2020-03-23 06:53 UTC, Enjection requested changes

2020-03-23 06:53 UTC, Enjection commented on include/websocket/handlers/add_cis_cron.h
> +        tr.send_error(dto::auth_error_login_required{}, "Login required.");
Probably should return on error?

2020-03-23 06:53 UTC, Enjection commented on src/websocket/handlers/change_pass.cpp
> +        bool ok = authentication_handler.change_pass(
Shouldn't check old pass if user has admin rights

2020-03-23 06:53 UTC, Enjection commented on src/websocket/handlers/get_project_permissions.cpp
> +    for(auto [project_name, project_rights_ex] : permissions)
User auto& instead of auto to avoid copying.

2020-03-23 06:53 UTC, Enjection commented on src/websocket/handlers/get_user_permissions.cpp
> +    for(auto [project_name, project_rights] : permissions)
User auto& instead of auto.

2020-03-23 08:09 UTC, sergeyboyko0791 commented
The issues were fixed

2020-03-24 07:03 UTC, Enjection approved these changes

2020-03-26 06:58 UTC, merged