Feature/guest rights/98
tomsksoft-llc/cis1-webui-native-srv-cpp pull request #99
Opened 2020-02-05 08:17 UTC by sergeyboyko0791

2020-02-05 11:46 UTC, Enjection requested changes

2020-02-05 11:46 UTC, Enjection commented on include/websocket/handlers/add_user.h
> +} // namespace
```cpp} // namespace```

should be

```cpp} // namespace websocket::handlers```

2020-02-05 11:46 UTC, Enjection commented on include/request_context.h
> +    cln_info_holder cln_info = guest_info{};
Better should use full name ```client_info``` and ```client_info_holder```

2020-02-05 11:46 UTC, Enjection commented on src/http/webhooks_handler.cpp
> +    const std::string active_token = std::visit(
Probably better wrap ctx.cln_info usage somehow, instead of writing same visitor every time

2020-02-05 11:46 UTC, Enjection commented on src/websocket/handlers/logout.cpp
> -        if(req.token == ctx.active_token)
You should clear ```ctx.active_token``` and ```ctx.username``` because they persists for all requests in same websocket connection.

2020-02-07 06:59 UTC, Enjection approved these changes

2020-02-07 11:35 UTC, Enjection approved these changes

2020-02-11 04:58 UTC, Neverhooda approved these changes

2020-02-18 03:09 UTC, merged